    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.KEYSTORE_FILE }}
        alias: ${{ secrets.KEY_ALIAS }}
        keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: "34.0.0"

    # NUOVO STEP: Rinomina il file firmato
    - name: Rename Signed APK
      run: mv ${{ steps.sign_app.outputs.signedReleaseFile }} app/build/outputs/apk/release/PhotoTinder.apk

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      with:
        tag_name: latest-build
        name: "PhotoTinder - Latest Build"
        body: "Signed apk ready to install. Known issues: missing icon, missing translations for some languages"
        draft: false
        prerelease: false
        # Carichiamo solo il file rinominato
        files: app/build/outputs/apk/release/PhotoTinder.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
